// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/synctv-org/vendors/internal/conf"
	"github.com/synctv-org/vendors/internal/registry"
	"github.com/synctv-org/vendors/internal/server/bilibili"
	"github.com/synctv-org/vendors/service/bilibili"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confRegistry *conf.Registry, bilibiliConfig *conf.BilibiliConfig, logger log.Logger) (*kratos.App, func(), error) {
	bilibiliService := bilibili.NewBilibiliService(bilibiliConfig)
	grpcGatewayServer := server.NewGRPCServer(confServer, bilibiliService, logger)
	httpServer := server.NewHTTPServer(confServer, bilibiliService, logger)
	registrar := registry.NewRegistry(confRegistry)
	app := newApp(logger, grpcGatewayServer, httpServer, registrar)
	return app, func() {
	}, nil
}
