// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/synctv-org/vendors/conf"
	"github.com/synctv-org/vendors/internal/registry"
	"github.com/synctv-org/vendors/internal/server"
	"github.com/synctv-org/vendors/service/alist"
	"github.com/synctv-org/vendors/service/bilibili"
	"github.com/synctv-org/vendors/service/emby"
	"github.com/synctv-org/vendors/service/webdav"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(grpcServer *conf.GrpcServer, confRegistry *conf.Registry, alistConfig *conf.AlistConfig, bilibiliConfig *conf.BilibiliConfig, embyConfig *conf.EmbyConfig, webdavConfig *conf.WebdavConfig, logger log.Logger) (*kratos.App, func(), error) {
	bilibiliService := bilibili.NewBilibiliService(bilibiliConfig)
	alistService := alist.NewAlistService(alistConfig)
	embyService := emby.NewEmbyService(embyConfig)
	webdavService := webdav.NewWebdavService(webdavConfig)
	grpcGatewayServer := server.NewGRPCServer(grpcServer, bilibiliService, alistService, embyService, webdavService)
	registrar := registry.NewRegistry(confRegistry)
	app := newApp(logger, grpcGatewayServer, registrar)
	return app, func() {
	}, nil
}
