name: release_dev

on:
  workflow_dispatch:

jobs:
  release_dev:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: ["1.21"]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          bash script/build.sh -v dev -p "windows,linux,darwin"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          title: "Dev Build"
          prerelease: true
          files: |
            build/*
